# coding: utf-8

"""
    dawpy server

    This is the daw server api  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.playlist import Playlist  # noqa: E501
from swagger_client.rest import ApiException


class TestPlaylist(unittest.TestCase):
    """Playlist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlaylist(self):
        """Test Playlist"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.playlist.Playlist()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
