# coding: utf-8

"""
    dawpy server

    This is the daw server api  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_pattern_to_song_map_playlist_add_index_pattern_name_post(self):
        """Test case for add_pattern_to_song_map_playlist_add_index_pattern_name_post

        Add Pattern To Song Map  # noqa: E501
        """
        pass

    def test_configure_pattern_pattern_pattern_name_patch(self):
        """Test case for configure_pattern_pattern_pattern_name_patch

        Configure Pattern  # noqa: E501
        """
        pass

    def test_configure_plugin_plugin_plugin_name_patch(self):
        """Test case for configure_plugin_plugin_plugin_name_patch

        Configure Plugin  # noqa: E501
        """
        pass

    def test_create_pattern_pattern_post(self):
        """Test case for create_pattern_pattern_post

        Create Pattern  # noqa: E501
        """
        pass

    def test_create_playlist_playlist_post(self):
        """Test case for create_playlist_playlist_post

        Create Playlist  # noqa: E501
        """
        pass

    def test_get_pattern_by_name_pattern_pattern_name_get(self):
        """Test case for get_pattern_by_name_pattern_pattern_name_get

        Get Pattern By Name  # noqa: E501
        """
        pass

    def test_get_playlist_daw_get(self):
        """Test case for get_playlist_daw_get

        Get Playlist  # noqa: E501
        """
        pass

    def test_get_plugin_by_name_plugin_plugin_name_get(self):
        """Test case for get_plugin_by_name_plugin_plugin_name_get

        Get Plugin By Name  # noqa: E501
        """
        pass

    def test_get_plugins_plugin_get(self):
        """Test case for get_plugins_plugin_get

        Get Plugins  # noqa: E501
        """
        pass

    def test_register_plugin_plugin_post(self):
        """Test case for register_plugin_plugin_post

        Register Plugin  # noqa: E501
        """
        pass

    def test_render_playlist_daw_render_get(self):
        """Test case for render_playlist_daw_render_get

        Render Playlist  # noqa: E501
        """
        pass

    def test_save_playlist_daw_save_get(self):
        """Test case for save_playlist_daw_save_get

        save playlist  # noqa: E501
        """
        pass

    def test_update_pattern_pattern_pattern_name_put(self):
        """Test case for update_pattern_pattern_pattern_name_put

        Update Pattern  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
