name: dawpy
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
      - typer
      - fastapi
      - uvicorn[standard]
      - urllib3
      - setuptools
      - python_dateutil
      - six
      - certifi