# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2021-01-15T11:04:18+00:00

from __future__ import annotations

from typing import List

from fastapi import FastAPI
from fastapi.logger import logger

from models import Daw, Pattern, Playlist, Plugin

import uvicorn

app = FastAPI(
    title='dawpy server',
    description='This is the daw server api',
    license={
        'name': 'Apache 2.0',
        'url': 'http://www.apache.org/licenses/LICENSE-2.0.html',
    },
    version='0.1.0',
)

daw: Daw = Daw()


@app.get('/daw', response_model=Daw)
def get_playlist() -> Daw:
    """
    get current playlist
    """
    logger.warn(f"getting daw: {daw.__dict__}")
    return daw


@app.get('/daw/render', response_model=str)
def render_playlist() -> str:
    """
    render current playlist
    """
    pass


# todo save, load
# todo much more :) works nicely


@app.post('/pattern', response_model=None)
def create_pattern(body: Pattern) -> None:
    """
    create a new pattern
    """
    pass


@app.get('/pattern/{pattern_name}', response_model=Pattern)
def get_pattern_by_name(pattern_name: str) -> Pattern:
    """
    Get pattern by name
    """
    pass


@app.put('/pattern/{pattern_name}', response_model=Pattern)
def update_pattern(pattern_name: str) -> Pattern:
    """
    update a pattern by name
    """
    pass


@app.patch('/pattern/{pattern_name}', response_model=None)
def configure_pattern(pattern_name: str) -> None:
    """
    Configure Pattern
    """
    pass


@app.post('/playlist', response_model=None)
def create_playlist(body: Playlist) -> None:
    """
    create a new playlist
    """
    pass


@app.post('/playlist/add/{index}/{pattern_name}', response_model=Pattern)
def add_pattern_to_song_map(pattern_name: str, index: int) -> Pattern:
    """
    add pattern to songmap at index
    """
    pass


@app.get('/plugin', response_model=List[Plugin])
def get_plugins() -> List[Plugin]:
    """
    get registered plugins
    """
    return daw.registered_plugins


@app.post('/plugin', response_model=Daw)
def register_plugin(body: Plugin) -> None:
    """
    register a new plugin
    """
    logger.warn(f"registering Plugin {body.__dict__}")
    daw.register_plugin(body)
    return daw


@app.get('/plugin/{plugin_name}', response_model=Plugin)
def get_plugin_by_name(plugin_name: str) -> Plugin:
    """
    Get plugin by name
    """
    return daw.get_plugin_by_name(plugin_name)


@app.patch('/plugin/{plugin_name}', response_model=None)
def configure_plugin(plugin_name: str) -> None:
    """
    Configure Plugin
    """
    pass


if __name__ == '__main__':
    uvicorn.run(app, reload=True)
