rem this file is generated by urknall.py from urknall.yaml
@echo on
call conda env remove -n dawpy
call conda create -y -n dawpy
call conda activate dawpy
call conda install -y -c conda-forge python=3.8
call conda install -y -c conda-forge pip
call conda install -y -c conda-forge rust=1.47.0
call conda install -y -c conda-forge openjdk=11.0.6
call conda install -y -c conda-forge maven=3.6.0
call conda install -y -c conda-forge nodejs=10.13.0
call curl.exe --output lib\jfugue-5.0.9.jar http://www.jfugue.org/jfugue-5.0.9.jar
call pip install typer
call pip install pickledb
call pip install pydantic
call cargo install pyoxidizer