# coding: utf-8

"""
    dawpy server

    This is the daw server api  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Plugin(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'dll_path': 'str',
        'preset_path': 'str'
    }

    attribute_map = {
        'name': 'name',
        'dll_path': 'dll_path',
        'preset_path': 'preset_path'
    }

    def __init__(self, name=None, dll_path=None, preset_path=None):  # noqa: E501
        """Plugin - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._dll_path = None
        self._preset_path = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if dll_path is not None:
            self.dll_path = dll_path
        if preset_path is not None:
            self.preset_path = preset_path

    @property
    def name(self):
        """Gets the name of this Plugin.  # noqa: E501


        :return: The name of this Plugin.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Plugin.


        :param name: The name of this Plugin.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def dll_path(self):
        """Gets the dll_path of this Plugin.  # noqa: E501


        :return: The dll_path of this Plugin.  # noqa: E501
        :rtype: str
        """
        return self._dll_path

    @dll_path.setter
    def dll_path(self, dll_path):
        """Sets the dll_path of this Plugin.


        :param dll_path: The dll_path of this Plugin.  # noqa: E501
        :type: str
        """

        self._dll_path = dll_path

    @property
    def preset_path(self):
        """Gets the preset_path of this Plugin.  # noqa: E501


        :return: The preset_path of this Plugin.  # noqa: E501
        :rtype: str
        """
        return self._preset_path

    @preset_path.setter
    def preset_path(self, preset_path):
        """Sets the preset_path of this Plugin.


        :param preset_path: The preset_path of this Plugin.  # noqa: E501
        :type: str
        """

        self._preset_path = preset_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Plugin, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Plugin):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
